BASEURL = "https://api.dabablane.com/api"
BASEURLBACK = "https://api.dabablane.com/api/back/v1"
BASEURLFRONT = "https://api.dabablane.com/api/front/v1"


blane_keywords = [
    "blane",
    "blanes",
    "dabablane",
    "reservation",
    "booking",
    "book",
    "reserve",
    "restaurant",
    "spa",
    "activity",
    "massage",
    "food",
    "eat",
    "dine",
    "activities",
    "entertainment",
    "wellness",
    "relax",
    "casablanca",
    "morocco",
    "maroc",
    "price",
    "cost",
    "available",
    "time slot",
    "appointment",
    "order",
    "delivery",
    "table",
    "treatment",
    "service",
    "deal",
    "offer",
    "discount",
    "photo shoot",
    "photography",
    "studio",
    "event",
    "venue",
    "location",
]

location_keywords = [
    "anfa",
    "hay hassani",
    "ain chock",
    "mers sultan",
    "sidi bernoussi",
    "moulay rachid",
    "casablanca",
    "morocco",
    "maroc",
    "near me",
    "my area",
    "district",
    "neighbourhood",
    "location",
    "where",
    "corniche",
    "centre ville",
    "medina",
    "maârif",
    "gauthier",
]

greeting_keywords = [
    "hello",
    "hi",
    "hey",
    "bonjour",
    "salut",
    "salam",
    "good morning",
    "good afternoon",
    "good evening",
    "how are you",
    "start",
    "begin",
]

irrelevant_keywords = [
    "weather",
    "politics",
    "news",
    "stock market",
    "crypto",
    "bitcoin",
    "programming",
    "code",
    "technical support",
    "computer",
    "software",
    "medicine",
    "health advice",
    "legal advice",
    "homework",
    "study",
    "recipe",
    "cooking tutorial",
    "travel outside morocco",
]


district_map = {
    "anfa": [
        "bourgogne",
        "sidi belyout",
        "centre ville",
        "médina",
        "maârif",
        "ain diab",
        "corniche",
        "gauthier",
        "racine",
        "palmier",
        "triangle d'or",
        "oasis",
        "cil",
    ],
    "hay hassani": ["hay hassani", "oulfa", "errahma", "lissasfa"],
    "aïn chock": ["aïn chock", "sidi maârouf", "californie", "polo"],
    "aïn sebaâ - hay mohammadi": [
        "aïn sebaâ",
        "hay mohammadi",
        "roches noires",
        "belvédère",
    ],
    "al fida - mers sultan": ["al fida", "mers sultan", "derb sultan", "habous"],
    "sidi bernoussi - sidi moumen": ["sidi bernoussi", "sidi moumen", "zenata"],
    "moulay rachid - ben m'sick": [
        "moulay rachid",
        "sidi othmane",
        "ben m'sick",
        "sbata",
    ],
    "surroundings": [
        "bouskoura",
        "la ville verte",
        "dar bouazza",
        "mohammedia",
        "bouznika",
    ],
}
